### PR TITLE
Updated the instructions for requesting tech review.

### PR DESCRIPTION
**Pull request by adahms**
Updated the instructions for requesting a tech review as follows - 

* Changed the review group to @redhataccess/eud-tech-review
* Clarified a point of confusion around a 'Request review' button

### CODE REVIEW

**Comment by adahms** [comment]
Thanks @stoobie!

Moving to tech review.

**Comment by adahms** [comment]
@redhataccess/eud-tech-review - Please review for technical completeness and accuracy.

**Comment by benradey** [comment]
Perfect!

**Comment by adahms** [comment]
@redhataccess/eud-tech-review - ready to merge.

**Pull request merged**
