### PR TITLE
Sling model updates

### PR DESCRIPTION
**Pull request by carlosmunoz**
Refactor a few parts of the api (nothing that should change how it's used) and add more methods to the `SlingResource` class.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
Thanks @jmarrero I hadn't put this one up for review yet as I was trying to get the code coverage to increase (you should have caught that :wink: ). I'll ask for a second pass once I have time to finish that.

**Comment by jmarrero** [comment]
Sounds good. yeah I missed the negative test coverage.

**Comment by carlosmunoz** [comment]
@jmarrero I finally got it to increase code coverage!! Please review again.

**Comment by carlosmunoz** [comment]
cool @jmarrero ... happy to have that discussion offline. I went with a short name initially for readability and conciseness, but also happy to see it changed if required.

**Pull request merged**
