### PR TITLE
Ccs 3040 products ui

### PR DESCRIPTION
**Pull request by xdavidson**
* UI changes to introduce Products and Versions
* Add a vertical navigation on the left side
* Restructure admin panel.

### CODE REVIEW

**Comment by jmarrero** [comment]
@xdavidson Looks like the snapshots did not get updated when you did the last push.
yarn test -u and commit the changes should fix it.

**Comment by xdavidson** [comment]
> @xdavidson Looks like the snapshots did not get updated when you did the last push.
> yarn test -u and commit the changes should fix it.

pushed!

**Comment by jmarrero** [comment]
@xdavidson we got codecov back. We need more tests added to this PR.

**Comment by xdavidson** [comment]
> * There are a bunch of linter errors, we must fix those before merging. Please install the tslint plugin on vscode. If you have the updated linter and vscode all the lint warnings should pop up in yellow.
> * In your merge request you overwrite the yarn.lock that updates a bunch dependencies and it goes back to the old ones.
> * With the updated deps I see the product listing and navlinks tests fail with this error:
>   **only absolute urls are supported**
> * There is a lot of unused methods in navlinks aswell of unused imports in many of the changes files we should clean up that. VSCode will point out the unused methods and code.
> * Also noticed a few commented out lines of code, any commented out lines should just be removed.
> 
> @xdavidson Let me know if you want to work together on these.

Joseph, the above comments should have been addressed! I also increased the coverage by 0.27%.

**Comment by jmarrero** [comment]
@xdavidson awesome job in all this work! Very nice stuff on the tests. You are free to merge now, make sure to clean up the commit message when you click on squash and merge so we have a tidy git log.

**Pull request merged**
