### PR TITLE
FCCEUD-46: Update the module on prerequisites

### PR DESCRIPTION
**Pull request by theashiot**

### CODE REVIEW

**Comment by theashiot** [comment]
@redhataccess/pantheon-developers Please review for technical completeness and accuracy.

**Comment by benradey** [comment]
Well, no technical changes here, so review complete :)

**Review by robin-owen — APPROVED** [review]

**Comment by theashiot** [comment]
Thanks @robin-owen for the review.

@redhataccess/pantheon-developers. Please review and merge.

best,

ashwin

**Comment by stoobie** [comment]
@anarang This one is also ready for merging.

**Review by anarang — APPROVED** [review]
no tech changes here, approving this one too as it has been pending for long.

**Comment by anarang** [comment]
@stoobie ack, done.

**Pull request merged**
