### PR TITLE
FCCEUD-53: Declare the :LinkToSearchPage: attribute

### PR DESCRIPTION
**Pull request by theashiot**
* Declared the attribute LinkToSearchPage with the present search page
url

### CODE REVIEW

**Comment by theashiot** [comment]
Hi @redhataccess/pantheon-developers can you please check this PR for technical correctness?

many thanks,

ashwin

**Comment by benradey** [comment]
:+1:

**Comment by theashiot** [comment]
@robin-owen has approved this from docs perspective.

**Comment by theashiot** [comment]
@redhataccess/pantheon-developers can you please merge this PR?

@robin-owen has approved this from docs perspective but is unable at the moment to approve via GH.

best,

ashwin

**Review by benradey — APPROVED** [review]
Okie dokie, fair enough, I can bring it in. Thanks!

**Pull request merged**
