### PR TITLE
README-typo Fixing some issues with line breaks in code examples in R…

### PR DESCRIPTION
**Pull request by stoobie**
Fixing some line break issues with code examples in README.

@redhataccess/pantheon-developers Please review. These are just typo fixes. If all looks good, you can go ahead and merge.

### CODE REVIEW

**Review by benradey — APPROVED** [review]

**Comment by benradey** [comment]
@stoobie It looks like somehow, we have a failing check in our project and that is preventing us from making this merge at the moment. This issue is unrelated to your PR so please just sit tight for a moment.

**Comment by benradey** [comment]
@stoobie The underlying problem that was preventing your merge has been fixed, but it looks like the check is still failing. Can you please make another commit for this PR, and we'll see if that resets the mechanism?

**Comment by stoobie** [comment]
> @stoobie The underlying problem that was preventing your merge has been fixed, but it looks like the check is still failing. Can you please make another commit for this PR, and we'll see if that resets the mechanism?

OK, @benradey , I made another commit. Just added a space at the end of a line.

**Review by benradey — APPROVED** [review]

**Comment by benradey** [comment]
@stoobie Looks like that fixed it, thanks for your patience!

**Pull request merged**
