### PR TITLE
Added three new modules to the pantheon2.yml file:

### PR DESCRIPTION
**Pull request by adahms**
* con_pantheon.adoc
 * con_user-roles.adoc
 * proc_versioning_a_product.adoc

### CODE REVIEW

**Comment by adahms** [comment]
@redhataccess/pantheon-developers - Please review for technical completeness and accuracy.

**Comment by benradey** [comment]
Marking as tech review complete.

For the future - I think for changes such as this, where there is no update to any doc content, it would be OK to bypass the tech review step and just add a note to that effect when requesting a merge.

Regardless, I appreciate your spirit of sticking to the process even in this case. :)

**Comment by adahms** [comment]
Thanks, @benradey - I guess this one is ready for merge, then.

Can you do the honours?

**Comment by stoobie** [comment]
@redhataccess/pantheon-developers This PR is ready for merge. Is someone available?

**Comment by stoobie** [comment]
@anarang Can you please approve and merge this one too?

**Review by anarang — APPROVED** [review]
Approving this one, as tech review has been completed already.

**Comment by anarang** [comment]
@stoobie approved and merged this one too. thanks. :)

**Pull request merged**
