### PR TITLE
Revert mod variants in toc

### PR DESCRIPTION
**Pull request by benradey**
Moving variant code into the assembly api, and fixing xref functionality

### CODE REVIEW

**Comment by xdavidson** [comment]
I checked out the remote branch and deployed locally. Assembly variant API now through an exception:
  java.lang.NullPointerException
	at com.redhat.pantheon.servlet.assembly.AssemblyVariantJsonServlet.resourceToMap(AssemblyVariantJsonServlet.java:198)

**Comment by benradey** [comment]
@xdavidson I fixed the NPE, please re-review.

**Comment by xdavidson** [comment]
I deployed the latest code from your branch. the 500 error is fixed. Thank you for that. But "included_in_guides" and "isPartOf" no longer works. Both are empty on the module variant API.

**Comment by benradey** [comment]
Thanks @xdavidson, I just pushed another commit. I haven't tested it, but I think it has a good chance of fixing it. Can you verify?

**Comment by xdavidson** [comment]
the issue regarding "included_in_guides" and "isPartOf" is now fixed.

**Review by xdavidson — APPROVED** [review]

**Pull request merged**
