### PR TITLE
FCCEUD-22 how to log in to Pantheon II

### PR DESCRIPTION
**Pull request by emarcusRH**
draft - basic steps for loging in to Pantheon II

### CODE REVIEW

**Comment by benradey** [comment]
@emarcusRH Did you intend the pantheon.cee.redhat.com link to be a placeholder? The current URL for Pantheon 2 is different, although it may change in the future.

**Comment by emarcusRH** [comment]
> @emarcusRH Did you intend the pantheon.cee.redhat.com link to be a placeholder? The current URL for Pantheon 2 is different, although it may change in the future.

Yes, until we have an actual functional URL, that can be the placeholder

**Comment by benradey** [comment]
@emarcusRH It looks like we were having some trouble with Travis when you opened the PR, hopefully it's resolved now, can you make another commit to see if that kickstarts things?

**Comment by benradey** [comment]
Merged as #192

**Pull request closed without merging**
