### PR TITLE
FCCEUD-64 Added concept module explaining snippet support Pantheon 2.

### PR DESCRIPTION
**Pull request by stoobie**
Resolves https://issues.redhat.com/browse/FCCEUD-64.

### CODE REVIEW

**Comment by stoobie** [comment]
@redhataccess/eud-tech-review Please review for technical accuracy.

**Comment by RichardHoch** [comment]
@stoobie -- Acknowledging your request. Would prefer to peer review after technical review is complete. Please tag me again when that review is complete.

**Review by noopurmath3 — APPROVED** [review]
LGTM 👍

**Comment by stoobie** [comment]
@RichardHoch SME has approved. Please do peer review.

**Comment by RichardHoch** [comment]
LGTM

**Comment by stoobie** [comment]
@noopurmath3 Can you please merge this?

**Comment by stoobie** [comment]
@noopurmath3 I just fixed a small bug, so the PR needs you to approve it again, and then you can go ahead and merge it. :)

**Review by noopurmath3 — APPROVED** [review]

**Pull request merged**
