### PR TITLE
FCCEUD-17 & FCCEUD-16: OS and browser prerequisites.

### PR DESCRIPTION
**Pull request by stoobie**
This pull request addresses both FCCEUD-17 and FCCEUD-16.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@benradey assigning this to you for review, and trying to assign to Andrew as well but I cannot find his github alias.

**Comment by benradey** [comment]
@anarang @noopurmath3 Are we actually testing compatibility against the OSes and browsers that Steve indicates?

**Comment by anarang** [comment]
@benradey yes, Pantheon v2 is compatible with all the browsers as mentioned. UI works as expected on Safari 13.0.2, Firefox 71.0, Chrome 78. 
As for the uploader, we need to tweak the uploader install instructions so that it works on all OS(RHEL7,8, Fedora 30+, MacOS), otherwise when we try to upload using the uploader script (not as a command), it works on all platforms. Discussed the same with @jmarrero as well before the PTO.

**Comment by benradey** [comment]
Thanks Anisha. So @stoobie, it sounds like although macOS support is a goal, having that in the documentation *today* is not entirely accurate. I'll leave it to you to decide if you'd like to leave it in the documentation or not. I'll go ahead and approve the PR as-is, and if you want to make an additional commit to update the document, that's fine too.

**Comment by benradey** [comment]
@stoobie It looks like we were having some trouble with Travis when you opened the PR, hopefully it's resolved now, can you make another commit to see if that kickstarts things?

**Comment by stoobie** [comment]
> As for the uploader, we need to tweak the uploader install instructions so that it works on all OS(RHEL7,8, Fedora 30+, MacOS), otherwise when we try to upload using the uploader script (not as a command), it works on all platforms.

@anarang To me it sounds like macOS is supported. The exact way in which you upload files might or might not be different on macOS than on Linux/Windows by the time this guide is published, but the bottom line is that you do provide macOS users with a way to upload files. That's what's important for defining the prerequisites here. When we describe how to upload files we can create a separate procedure for Mac if necessary.

> @stoobie It looks like we were having some trouble with Travis when you opened the PR, hopefully it's resolved now, can you make another commit to see if that kickstarts things?

@benradey, it appears to me that the PR passed Travis and can now be merged.

**Comment by benradey** [comment]
Two things:

1. Since my original comment, I remembered that for milestone 2, the only officially-supported use of the uploader is the server-side git sync service. Client-side use of the uploader might be a nice bonus but it is not officially supported *yet,* so the documentation is correct as-is.
2. We have only 1 out of 2 required checks so the merge is not yet possible. I'm testing a workaround with our other open PR, we'll see if that works.

**Comment by benradey** [comment]
Merged as #193

**Comment by anarang** [comment]
@stoobie yes, that's right. ack.

**Pull request closed without merging**
