### PR TITLE
CCS-3891 - fix metadata display for draft and published

### PR DESCRIPTION
**Pull request by xdavidson**
This PR introduces the following changes:
  * fix empty metadata when there are both draft and published versions
  * add ids to buttons for automation suite

### CODE REVIEW

**Comment by benradey** [comment]
@xdavidson could we schedule some time to do a live walkthrough of this PR?

**Comment by xdavidson** [comment]
> @xdavidson could we schedule some time to do a live walkthrough of this PR?

Ben, I scheduled a 30 mins meeting for us today.

**Comment by xdavidson** [comment]
> > @xdavidson could we schedule some time to do a live walkthrough of this PR?
> 
> Ben, I scheduled a 30 mins meeting for us today.

Ben, 

I refactored the code per our discussion in the meeting.

**Review by benradey — APPROVED** [review]
I can wrap my head around most of it, and it appears to work locally. I tested documents with draft only, released only, and both draft and released, and each scenario seems to work. Thanks @xdavidson !

**Pull request merged**
